### ISSUE TITLE
Error creating a plot

### ISSUE THREAD

**Issue by pawelk1337** [Whitescan/PlayerPlot#11]
[17:47:55 INFO]: AshKetchumPL issued server command: /plot claim
[17:47:55 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlayerPlot v1.22.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:962) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at org.bukkit.craftbukkit.v1_19_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[purpur-1.19.2.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2386) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$21(ServerGamePacketListenerImpl.java:2340) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R2/CraftWorld
        at de.whitescan.playerplot.border.Border.show(Border.java:41) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.border.Border.showBorder(Border.java:75) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.border.Border.showPlot(Border.java:62) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.listener.PlotScanner.showPlot(PlotScanner.java:44) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.command.CommandPlot.processClaim(CommandPlot.java:216) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.command.CommandPlot.onCommand(CommandPlot.java:60) ~[PlayerPlot-1.22.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R2.CraftWorld
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:179) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:126) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at de.whitescan.playerplot.border.Border.show(Border.java:41) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.border.Border.showBorder(Border.java:75) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.border.Border.showPlot(Border.java:62) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.listener.PlotScanner.showPlot(PlotScanner.java:44) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.command.CommandPlot.processClaim(CommandPlot.java:216) ~[PlayerPlot-1.22.0.jar:?]
        at de.whitescan.playerplot.command.CommandPlot.onCommand(CommandPlot.java:60) ~[PlayerPlot-1.22.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by SuperPou1** [comment]
i have the same issue :(

**Comment by at0mweb** [comment]
same issue
