### ISSUE TITLE
errors when envoking plot upgrade, plot scan, etc.

### ISSUE THREAD

**Issue by vicalop** [Whitescan/PlayerPlot#7]
Stopped working on 1.19.3
Worked before.

Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R1.CraftWorld
        at de.whitescan.playerplot.border.Border.show(Border.java:41) ~[PlayerPlot-1.21.0.jar:?]
        at de.whitescan.playerplot.border.Border.showBorder(Border.java:75) ~[PlayerPlot-1.21.0.jar:?]
        at de.whitescan.playerplot.border.Border.showPlot(Border.java:62) ~[PlayerPlot-1.21.0.jar:?]
        at de.whitescan.playerplot.plot.PlotScanner.showPlot(PlotScanner.java:43) ~[PlayerPlot-1.21.0.jar:?]
        at de.whitescan.playerplot.plot.CommandPlot.processUpgrade(CommandPlot.java:358) ~[PlayerPlot-1.21.0.jar:?]
        at de.whitescan.playerplot.plot.CommandPlot.lambda$onCommand$0(CommandPlot.java:79) ~[PlayerPlot-1.21.0.jar:?]
        at de.whitescan.playerplot.plot.CommandPlot.processStandingAction(CommandPlot.java:139) ~[PlayerPlot-1.21.0.jar:?]
        at de.whitescan.playerplot.plot.CommandPlot.processPlotAction(CommandPlot.java:131) ~[PlayerPlot-1.21.0.jar:?]
        at de.whitescan.playerplot.plot.CommandPlot.onCommand(CommandPlot.java:62) ~[PlayerPlot-1.21.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 23 more

**Comment by Whitescan** [comment]
Unfortunately this plugin requires NMS for the Worldboarders. Meaning it only works on the specific version (1.19).
It will be upgraded eventually.
