### ISSUE TITLE
Instruction error

### ISSUE THREAD

**Issue by BigAppleClass** [Whitescan/PlayerPlot#8]
[01:49:29] [Server thread/INFO]: Naive_god issued server command: /plot free
[01:49:29] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlayerPlot v1.21.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-328]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-328]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2290) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2252) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1445) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-328]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R1/CraftWorld
	at de.whitescan.playerplot.border.Border.show(Border.java:41) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.border.Border.showBorder(Border.java:75) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.border.Border.showPlot(Border.java:62) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.PlotScanner.showPlot(PlotScanner.java:43) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processFree(CommandPlot.java:234) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.lambda$onCommand$0(CommandPlot.java:70) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processStandingAction(CommandPlot.java:139) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processPlotAction(CommandPlot.java:131) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.onCommand(CommandPlot.java:62) ~[PlayerPlot-1.21.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R1.CraftWorld
	at de.whitescan.playerplot.border.Border.show(Border.java:41) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.border.Border.showBorder(Border.java:75) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.border.Border.showPlot(Border.java:62) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.PlotScanner.showPlot(PlotScanner.java:43) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processFree(CommandPlot.java:234) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.lambda$onCommand$0(CommandPlot.java:70) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processStandingAction(CommandPlot.java:139) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processPlotAction(CommandPlot.java:131) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.onCommand(CommandPlot.java:62) ~[PlayerPlot-1.21.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more
[01:49:41] [Server thread/INFO]: Naive_god issued server command: /plot claim
[01:49:45] [Server thread/INFO]: Naive_god issued server command: /plot claim
[01:49:52] [Server thread/INFO]: Naive_god issued server command: /plot free
[01:49:52] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'plot' in plugin PlayerPlot v1.21.0
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.dispatchCommand(CraftServer.java:929) ~[paper-1.19.3.jar:git-Paper-328]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.3.jar:git-Paper-328]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.3.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:313) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:297) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2290) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2252) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-328]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-328]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_19_R1/CraftWorld
	at de.whitescan.playerplot.border.Border.show(Border.java:41) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.border.Border.showBorder(Border.java:75) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.border.Border.showPlot(Border.java:62) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.PlotScanner.showPlot(PlotScanner.java:43) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processFree(CommandPlot.java:234) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.lambda$onCommand$0(CommandPlot.java:70) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processStandingAction(CommandPlot.java:139) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processPlotAction(CommandPlot.java:131) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.onCommand(CommandPlot.java:62) ~[PlayerPlot-1.21.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_19_R1.CraftWorld
	at de.whitescan.playerplot.border.Border.show(Border.java:41) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.border.Border.showBorder(Border.java:75) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.border.Border.showPlot(Border.java:62) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.PlotScanner.showPlot(PlotScanner.java:43) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processFree(CommandPlot.java:234) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.lambda$onCommand$0(CommandPlot.java:70) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processStandingAction(CommandPlot.java:139) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.processPlotAction(CommandPlot.java:131) ~[PlayerPlot-1.21.0.jar:?]
	at de.whitescan.playerplot.plot.CommandPlot.onCommand(CommandPlot.java:62) ~[PlayerPlot-1.21.0.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 23 more

**Comment by Whitescan** [comment]
Which server version are you running?
